name: CI - Frontend Build and Test

on:
  push:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clear Cache (Optional)
        uses: actions/cache@v3  # Added to clear cache before install
        with:
          path: []  # Empty path to disable caching
          key: ${{ runner.os }}-build-${{ hashFiles('**/package*.json') }}  # Cache key based on package.json changes

      - name: Install dependencies
        run: npm install

      - name: Build with verbose output (Optional)
        run: npm run build --verbose  # Added --verbose flag for debugging

      - name: Run tests
        run: npm test
